/**
 * Experience Data — Single source of truth for all professional experience entries
 * Used by About page and potentially other components
 */

export const EXPERIENCES = [
    {
        id: 'solana',
        company: 'Solana',
        role: 'Software Engineer Fellow',
        date: 'Jun 2026 - Present · 2 mos',
        location: 'Remote',
        logo: '/solana.svg',
        bullets: [
            '170+ API endpoints across 20+ route families — deployed entirely offline on Solana devnet.',
            '6 Docker services (Node.js/Hono, Next.js, PostgreSQL + Redis) — self-hosted signing, SOL fee payment, public devnet RPC.',
            'Traced a systemic webhook failure (Clerk → Svix → API → PostgreSQL) — restored platform access by manually reconciling org mapping.',
            '7 scheduled crons ingesting on-chain token supply, holder distributions, and wallet labels into AWS S3 Delta Lake via Databricks.',
            'Health monitoring across database, RPC, token ingestion, and analytics pipeline — 449 source files covered.',
        ],
        skills: ['Solana', 'Blockchain', 'TypeScript', 'Hono', 'Cloudflare Workers', 'Next.js', 'PostgreSQL', 'Redis', 'Docker', 'Clerk', 'Databricks', 'AWS S3', 'Delta Lake', 'Node.js', 'RPC', 'Webhook Architecture', 'System Reliability', 'Tokenomics'],
    },
    {
        id: 'kubernetes',
        company: 'Kubernetes (Official)',
        role: 'Open-Source Contributor & Developer, SIG Apps & SIG Cluster Lifecycle',
        date: 'Feb 2026 - Present · 6 mos',
        location: 'Remote',
        logo: '/kubernetes.png',
        bullets: [
            'SIG Apps (LWS) & SIG Cluster Lifecycle (kubespray) — controller-level fixes in Go for multi-host LLM serving.',
        ],
        skills: ['Golang (Go 1.25)', 'Ansible', 'Git', 'Go Modules', 'Go Code Generation', 'Structured Logging (klog/v2, zap)', 'Concurrent Programming', 'CRDs & Controller-Runtime', 'Kubernetes API Design', 'Client-Go', 'Admission Webhooks', 'Kubebuilder', 'RBAC', 'Docker & Containerization', 'Helm', 'Kustomize', 'Makefile Automation', 'GitHub Actions', 'Google Cloud Build (GCB)', 'KIND (Kubernetes in Docker)', 'Dependabot', 'Leader-Worker Pattern', 'GPU/TPU Accelerator Support', 'Gang Scheduling & Volcano Integration', 'Stateful Workload Orchestration', 'Kubernetes Enhancement Proposals (KEPs)', 'Unit / Integration / E2E Testing', 'Ginkgo & Gomega', 'Code Coverage (Goveralls)', 'Static Analysis & Security Auditing', 'Hugo & Genref', 'Ansible Core', 'Jinja2 & jmespath', 'Inventory Validation', 'Cluster Lifecycle (kubeadm)', 'Control Plane Management (etcd, kubelet)', 'Container Runtimes (containerd)', 'CNI (Calico, Cilium, Flannel)', 'Linux System Engineering (cgroups v1/v2)', 'systemd', 'GitLab CI', 'Vagrant & Terraform', 'Python', 'Root Cause Analysis', 'CNCF Open Source Workflow', 'Open Source Contribution'],
    },
    {
        id: 'vllm',
        company: 'vLLM',
        role: 'Open Source Research Contributor | llm-d (vLLM ecosystem)',
        date: 'May 2026 - Present · 3 mos',
        location: 'Remote',
        logo: '/vllm.png',
        bullets: [
            'Energy-Aware Endpoint Picker Plugin (EPP) — optimizes token-level routing across H100s and L4s.',
            'Multi-Objective Routing Engine — Kubernetes Gateway API GIE sidecar in Go with epsilon-constraint routing for energy + latency SLOs.',
            'Phase-aware disaggregated serving — dynamic scoring for compute-bound prefill vs memory-bound decode phases.',
            'Carbon-aware controller — real-time weight modulation via grid carbon intensity (SCI) and cluster thermal budgets.',
            'eBPF telemetry ingestion plane using DCGM/RAPL metrics — 8.6 MB distroless image, 101µs routing overhead.',
            '17.4% average reduction in LLM inference energy (up to 32.3% decode-heavy) vs round-robin scheduling.',
        ],
        skills: ['Go', 'Kubernetes', 'vLLM', 'eBPF', 'Telemetry', 'Distributed Systems', 'Energy Optimization', 'Carbon-Aware Computing', 'LLM Infrastructure', 'Controller-Runtime', 'Multi-Objective Routing'],
    },
    {
        id: 'deel',
        company: 'Deel',
        role: 'Machine Learning Research Assistant',
        date: 'Nov 2025 - Present · 9 mos',
        location: 'Remote',
        logo: '/deel.jpeg',
        bullets: [
            'Legal AI platform — RAG + ML classification + MCTS reasoning for Canadian worker classification.',
            'Multi-source research engine — Pinecone (dense), Elasticsearch (BM25), SearXNG (web), legislation DB; RRF fusion with Gemini 2.0 Flash cited answers.',
            'Random Forest on 700+ annotated cases — 88% accuracy (GridSearchCV), MCTS reasoning agent citing Sagaz v. 671122 Ontario.',
            'React 18/TypeScript/Tailwind v4 frontend — real-time search, factor-assessment UI, collapsible MCTS reasoning trees.',
            'Containerized full stack (FastAPI, Elasticsearch, Milvus+etcd+MinIO, SearXNG) — GitHub Actions CI/CD, 142 pytest tests passing.',
        ],
        skills: ['Python', 'Machine Learning', 'Gemini Embeddings', 'RAG (Retrieval-Augmented Generation)', 'scikit-learn', 'Random Forest Classifier', 'Model Evaluation', 'Pinecone Vector Database', 'MCTS Reasoning', 'Selenium', 'BeautifulSoup4', 'PyMuPDF', 'pdfplumber', 'pandas', 'numpy', 'Synthetic Data Generation', 'FastAPI', 'Uvicorn', 'Python asyncio', 'Pydantic', 'python-dotenv', 'tenacity', 'Docker', 'Docker Compose', 'Kubernetes (K8s/AKS)', 'GitHub Actions CI/CD', 'Azure', 'pytest', 'pytest-asyncio', 'System Integration Testing', 'Canadian Employment Law', 'CanLII', 'Worker Classification (Sagaz Test)', 'Elasticsearch', 'Milvus', 'SearXNG', 'React', 'TypeScript', 'Tailwind CSS', 'Recharts', 'Zustand', 'TanStack Query'],
    },
    {
        id: 'autodrive',
        company: 'Queen\'s AutoDrive Team',
        role: 'CAN Lead & Embedded System Engineer',
        date: 'Aug 2025 - Present · 8 mos',
        location: 'Kingston, Ontario, Canada',
        logo: '/autodrive.png',
        bullets: [
            'SAE Level-4 autonomous vehicle (Chevrolet Bolt) — multi-threaded ROS2 C++ node with CAN messaging + DBC parsing on Raspberry Pi 5.',
            '100+ vehicle control signals at 10-50ms cyclic rates across 4 isolated CAN networks (HS, Chassis, Low-Speed, Scoring).',
            'ISO-TP diagnostic messaging with XML-driven config — 85% reduction in diagnostic setup time.',
            'Lock-free MPMC queue for 200+ concurrent CAN signals — sub-2ms end-to-end latency.',
            'Safety-critical state machine with rolling counter + CRC validation — ISO 26262 ASIL-D compliance.',
        ],
        skills: ['Concurrent Programming/Multi-threading', 'CI/CD Pipelines', 'Engine Control Unit (ECU)', 'Docker', 'Embedded C/C++', 'ROS2 (Robot Operating System)', 'Raspberry Pi', 'V2X', 'RTOS', 'SELinux', 'Linux Device Driver', 'V2V', 'Controller Area Network (CAN) Protocol', 'Hardware Integration/Interfacing (Intrepid Control Systems APIs, libicsneo)', 'Signal Processing', 'Signal Encoding/Decoding', 'Git', 'Git Version Control & Submodules', 'Embedded Systems', 'Control Systems Design', 'Wireshark', 'Object-Oriented Design', 'Object-Oriented Programming (OOP)', 'CMake and Build Systems', 'Fast / Asynchronous Systems Logging', 'XML Parsing', 'DBC (CAN Database) Parsing', 'Bit-level Manipulation (Masking, Bit-shifting, Endianness)', 'High-Performance Logging & Formatting (spdlog, fmt)', 'Unit Testing & Behavior Verification', 'Concurrent Data Structures (MPMCQueue)', 'Thread-safe, Lock-free Programming'],
    },
    {
        id: 'engsoc',
        company: 'Engineering Society of Queen\'s University',
        role: 'Sci \'26 Vice-President, Equity Officer & ECE Discipline Club Treasurer',
        date: 'Sep 2024 - Present · 1 yr 7 mos',
        location: 'Kingston, Ontario, Canada',
        logo: '/engsoc.png',
        bullets: [
            'Co-lead 12 executives for Class of 2026 — event planning for 800+ students, Faculty Board advocacy.',
            'EngSoc Council voting member — governance decisions for 3,000+ engineering students.',
            'Equity Officer — embedded EDII-AS principles into elections, awards, and council operations.',
            'ECE Treasurer — $19,000 operating budget, 30% utilization efficiency, $9,000 net surplus.',
        ],
        skills: ['Team Leadership', 'Stakeholder Engagement', 'Logistics Coordination', 'Public Speaking', 'Student Advocacy', 'Strategic Communications', 'Project Management', 'Stakeholder Management', 'Policy Analysis and Governance', 'Event Planning & Management', 'Equity, Diversity & Inclusion (EDI/EDII-AS)', 'Financial Reporting & Analysis', 'Process Optimization & Tools Proficiency', 'Revenue Growth & Fundraising', 'Budget Management & Financial Stewardship', 'Stakeholder Communication & Vendor Management', 'Cost Reduction Strategies & Strategic Financial Planning', 'Grant Writing & Sponsorship Acquisition', 'Governance'],
    },
    {
        id: 'qhpc',
        company: 'Queen\'s High-Performance Computing',
        role: 'Co-Founder, COO, HR Lead & Financial Lead',
        date: 'Dec 2023 - Present · 2 yrs 4 mos',
        location: 'Kingston, Ontario, Canada',
        logo: '/qhpc.png',
        bullets: [
            'Co-founded Queen\'s first ratified HPC club — 40+ members, SC25/SC26 prep, $10K+ funding from Dell & Queen\'s Centre for Advanced Computing.',
            'Delivered HPC workshops — cluster architectures (Frontenac), Linux admin, MPI/OpenMP parallelization, benchmarking (HPL, HPCG, LAMMPS, Phasta).',
            'Built 4-week Sprint learning model with project cycles — distributed systems, performance monitoring, app tuning — documentation for 40+ members.',
            'Led 2026-27 executive recruitment via Breezy HR — structured interviews, EDII-AS compliance, 20+ shortlisted candidates.',
            'Managed $10K+ operating budget — 30% utilization efficiency, $9K net surplus, automated procurement analysis reducing cycle time by 20%.',
            'Assembled 8-node Raspberry Pi cluster — DHCP/TFTP network boot, NFS shared scratch storage.',
            'Built \'travelExpenseTracker\' Android app — SQLite auth, real-time spending analytics with MPAndroidChart.',
        ],
        skills: ['High-Performance Computing (HPC)', 'HPC Fundamentals', 'Cluster Architectures', 'Linux System Administration', 'Parallel Programming (MPI, OpenMP)', 'Benchmarking (HPL, HPCG, LAMMPS, Phasta)', 'Slurm Job Scheduling', 'Shell Scripting & Automation (Bash, Python)', 'Cluster Computing', 'Parallel Processing & Distributed Systems', 'Vim', 'Resource Optimization & Power Management', 'GPU-Accelerated Computing (NVIDIA L4)', 'Heterogeneous Computing', 'Network Boot (TFTP, NFS)', 'Raspberry Pi Clustering', 'Parallel SSH (pdsh)', 'Batch Scheduling', 'Resource Optimization', 'Project Management', 'Breezy HR & Recruitment', 'EDII-AS Governance', 'Budget Management ($10,000+)', 'Grant Writing & Sponsorship Acquisition', 'Stakeholder Engagement', 'Event Planning & Management', 'Logistics Coordination', 'Strategic Communications', 'Android Development (Kotlin/Java)', 'SQLite', 'MPAndroidChart', 'Financial Software Development', 'Expense Tracking Automation', 'Git'],
    },
    {
        id: 'essco',
        company: 'Engineering Student Societies\' Council of Ontario',
        role: 'FYIC Webmaster',
        date: 'Mar 2025 - Dec 2025 · 10 mos',
        location: 'Kingston, Ontario, Canada',
        logo: '/essco.png',
        bullets: [
            'Spearheaded FYIC website for 18+ universities — Next.js 15, Tailwind CSS, sub-second loads, 95+ Lighthouse score.',
            'Architected GitHub Actions CI/CD — automated type-checking, linting, zero-downtime Vercel deployments, 60% faster release cycles.',
            'Implemented automated CVE vulnerability scanning in CI pipeline for React Server Components.',
            'Integrated UserWay AI accessibility widget — WCAG 2.1 AA compliance.',
        ],
        skills: ['Next.js 15 (App Router)', 'React 18', 'TypeScript 5.8', 'Client/Server Architecture', 'Tailwind CSS 3', 'Material Tailwind', 'Responsive & Mobile-First Design', 'Framer Motion', 'GSAP', 'Three.js', 'React Three Fiber', 'Canvas Confetti', 'Lucide & Heroicons', 'Next.js API Routes', 'Nodemailer (SMTP)', 'React Hook Form', 'Environment Variable Management', 'Node.js Scripting (Sharp)', 'Image Optimization (WebP)', 'Bundle Size Optimization', 'GitHub Actions (CI/CD)', 'PostCSS & Autoprefixer', 'ESLint', 'Modular Component Design', 'SEO Best Practices', 'Software Lifecycle Management', 'Git', 'npm', 'CI/CD Pipelines', 'UI/UX Design', 'WCAG Accessibility'],
    },
    {
        id: 'qweb',
        company: 'Queen\'s University Web Development - QWeb',
        role: 'Full Stack Developer',
        date: 'Sep 2024 - Apr 2025 · 8 mos',
        location: 'Kingston, Ontario, Canada',
        logo: '/qweb.png',
        bullets: [
            'Designed and deployed full-stack e-learning platform — React.js, Node.js, Express.js, MongoDB — 100+ monthly active users.',
            'Improved front-end performance via lazy loading and memoization — 15% reduction in page render times for critical workflows.',
            'Built RESTful APIs with Node.js, Express.js, and MongoDB — CRUD operations, JWT auth, optimized indexing and pipeline queries.',
            'Collaborated in Agile teams to build client websites — 95% bug-free pre-deployment via Jest, unit and integration tests with Supertest.',
            'Built responsive, WCAG-compliant UIs from Figma mocks — ARIA attributes, CSS modules, full keyboard navigation and color contrast.',
            'Streamlined dev workflows with Git and Bitbucket CI/CD — seamless collaboration across 2 cross-functional teams.',
            'Containerized with Docker, deployed to AWS Fargate — 30% hosting cost reduction via efficient orchestration and RDS configs.',
        ],
        skills: ['React.js', 'Express.js', 'RESTful APIs', 'RESTful API Development', 'CI/CD Pipelines', 'Docker', 'Jira & Atlassian Integration', 'UI/UX Design', 'WCAG Accessibility', 'Amazon Web Services (AWS)', 'Automated Testing (Jest/Supertest)', 'MongoDB (Mongoose)', 'Full Stack Development (MERN Stack)', 'Node.js', 'Agile Methodologies', 'Stakeholder Management', 'React.js (Context API)', 'Git', 'Figma', 'JWT Authentication', 'AWS ECS', 'Containerization', 'Performance Optimization (Lazy Loading, Memoization)', 'Scalable System Architecture'],
    },
    {
        id: 'freelancer',
        company: 'Freelancer.com',
        role: 'Android App Development Freelancer',
        date: 'May 2024 - Aug 2024 · 4 mos',
        location: 'Remote',
        logo: '/freelancer.jfif',
        bullets: [
            'Developed ChillnCharm e-commerce Android app — 50+ products, MVVM + Clean Architecture, modular SDK codebase.',
            'Integrated Retrofit + FAKE STORE API for 50+ product listings and ROOM Database — 25% faster cached load times vs API calls.',
            'Built intuitive shopping UI — product search across 5+ categories, cart management, wish list persistence.',
            'Delivered demo project within deadlines — strong project management and adaptability to evolving client requirements.',
        ],
        skills: ['Android Development (Kotlin/Java)', 'MVVM Architecture', 'Clean Architecture', 'Repository Pattern', 'Retrofit & RESTful APIs', 'ROOM Database', 'Local Data Caching & Performance Optimization', 'Jetpack Components', 'Figma', 'Stakeholder Management', 'Agile Methodologies', 'Git', 'Project Management & Client Collaboration'],
    },
    {
        id: 'foresoon',
        company: 'Foresoon Computer Engineering Co. Ltd.',
        role: 'Electrical & Robotics Engineer Assistant',
        date: 'Aug 2023 - Sep 2023 · 2 mos',
        location: 'Hong Kong SAR',
        bullets: [
            'Assisted in designing assistive robotic feeding system — Kinova Gen3 6-DOF arm on Clearpath Jackal UGV for autonomous food transfer.',
            'Developed computer vision pipeline with Python OpenCV and ArUco markers — 3D pose estimation for real-time trajectory offsets.',
            'Co-designed modular ROS-based state machine — autonomous workflows with manual joystick overrides.',
            'Implemented Cartesian impedance controller with joint torque sensing for force-limited manipulation.',
        ],
        skills: ['Embedded C/C++', 'ROS2', 'SOLIDWORKS', 'Python', 'Git', 'Embedded Systems', 'Control Systems Design', 'Robot Operating System (ROS)'],
    },
    {
        id: 'arista',
        company: 'Arista Networks',
        role: 'Project Financial Management Intern',
        date: 'May 2023 - Aug 2023 · 4 mos',
        location: 'Hong Kong SAR',
        logo: '/arista.png',
        bullets: [
            'Conducted financial modeling & viability analysis using Excel — $2M client pilot and internal automation portfolios.',
            'Designed real-time Power BI dashboards — flagged $150K+ in potential overruns on 6 active projects in SAP S/4HANA.',
            'Prototyped Power Automate + SharePoint Dataverse workflow — streamlined data collection, 20% turnaround improvement.',
        ],
        skills: ['SAP S/4HANA', 'Microsoft Power BI', 'Process Optimization', 'Microsoft Power Automate', 'Budget Management', 'Project Management', 'SharePoint/Dataverse'],
    },
    {
        id: 'relectric',
        company: 'Queen\'s Relectric Car Team',
        role: 'Design Engineer',
        date: 'Jan 2023 - May 2023 · 5 mos',
        location: 'Kingston, Ontario, Canada',
        logo: '/relectric.jpg',
        bullets: [
            'Designed liquid-cooled battery enclosure for 16 LiFePO4 BMS in Jeep TJ conversion.',
            'Modeled 360mm × 637.5mm × 250mm aluminum 2024 alloy enclosure with SolidWorks — copper tubing (10mm) for heat dissipation.',
            'Conducted thermodynamic simulations and automated coolant pump activation via relay control — 40% thermal spike reduction vs passive cooling.',
        ],
        skills: ['Mathematical Modeling', 'Embedded C/C++', 'Arduino', 'Thermal Modeling', 'SOLIDWORKS', 'Git', 'Embedded Systems'],
    },
];

export const EDUCATION = [
    {
        id: 'queens',
        institution: 'Queen\'s University / Stephen J. R. Smith Faculty of Engineering and Applied Science',
        degree: 'Bachelor of Applied Science - BASc, Computer Engineering',
        date: 'Sep 2022 - May 2026',
        logo: '/queens_university.png',
        skills: ['Circuit Analysis', 'Mathematical Modeling', 'C (Programming Language)', 'Field-Programmable Gate Arrays (FPGA)', 'LTSpice', 'Verilog', 'VHDL', 'Logic Design', 'Machine Learning'],
    },
    {
        id: 'peths',
        institution: 'Pierre Elliott Trudeau High School',
        degree: 'High School Diploma',
        date: 'Sep 2018 - Jun 2022',
        logo: '/peths.jpg',
        bullets: ['Top 6 Admission Average: 93% (English, Advanced Functions, Calculus and Vectors, Physics, Chemistry, and Mandarin)'],
        skills: ['Arduino', 'Fritzing', 'Python', 'Raspberry Pi', 'Java'],
    },
];

export const CERTIFICATIONS = [
    {
        id: 'whmis',
        name: 'WHMIS 2015',
        issuer: 'Queen\'s University',
        date: 'Issued Feb 2023',
        logo: '/queens_university.png',
    },
    {
        id: 'ohsa',
        name: 'Occupational Health and Safety Awareness and Training Certificate',
        issuer: 'Queen\'s University',
        date: 'Issued Feb 2023',
        logo: '/queens_university.png',
    },
];