export interface Project {
  title: string;
  date: string;
  description: string;
  skills: string[];
  githubUrl?: string;
}

/**
 * All projects keyed by title.
 * Data extracted from app/project/page.js.
 */
export const PROJECTS: Record<string, Project> = {
  "G.O.S. Phytotron Sensor Node & AI Engine": {
    title: "G.O.S. Phytotron Sensor Node & AI Engine",
    date: "Jan 2026 - Present",
    description: "End-to-end development of an ultra-low-power IoT monitoring system for precision agriculture. Engineered custom 4-layer PCB (KiCad) with nRF52840 SoC, achieving 360nA quiescent current and 7+ year battery life. Integrated Zephyr RTOS Thread mesh networking for institutional-grade plant phenotyping.",
    skills: ["Embedded C/C++", "Python", "Zephyr RTOS", "KiCad", "nRF52840 SoC", "Thread Mesh", "PCB Design", "IoT"],
    githubUrl: "https://github.com/johnnietse/strawberry-farm",
  },
  "HPC Energy Optimization & DVFS Control System": {
    title: "HPC Energy Optimization & DVFS Control System",
    date: "Sep 2025 - Mar 20, 2026",
    description: "Dynamic frequency scaling system for miniMD reducing energy consumption during non-compute phases. Implemented a Beta-Adaptation algorithm and a 'Race-to-Idle' strategy for MPI communication phases, using Intel RAPL to validate energy efficiency on 32-core Xeon/EPYC nodes.",
    skills: ["C++", "Python", "MPI", "HPC", "Intel RAPL", "DVFS Control", "Beta-Adaptation", "Race-to-Idle"],
    githubUrl: "https://github.com/johnnietse/elec-498-group-30-2025-2026-proxy-app",
  },
  "Advanced Kubernetes SIG-Apps Contribution (lws)": {
    title: "Advanced Kubernetes SIG-Apps Contribution (lws)",
    date: "Feb 2026 - Present",
    description: "Upstream core contributor to the Kubernetes LeaderWorkerSet (LWS) controller. Implementing state-machine fixes for highly-available pod orchestration and improving API boundary safety for distributed GPU scheduling.",
    skills: ["Go", "Kubernetes", "Controller-Runtime", "SIG-Apps", "Distributed Systems", "API Design", "gRPC"],
    githubUrl: "https://github.com/johnnietse/lws",
  },
  "Energy-Aware Endpoint Picker Plugin (EPP)": {
    title: "Energy-Aware Endpoint Picker Plugin (EPP)",
    date: "Mar 2026 - Present",
    description: "Designed and implemented a Kubernetes-native Multi-Objective Routing Engine for the llm-d ecosystem. Integrates Carbon-Aware Controllers and eBPF telemetry to dynamically route LLM inference workloads based on real-time node power consumption.",
    skills: ["Go", "Kubernetes", "vLLM", "eBPF", "Telemetry", "Controller-Runtime", "Energy Optimization"],
    githubUrl: "https://github.com/johnnietse/llm-d-epp-Energy-Aware-Endpoint-Picker-Plugin-.git",
  },
  "Kubernetes SIG-Cluster-Lifecycle (kubespray)": {
    title: "Kubernetes SIG-Cluster-Lifecycle (kubespray)",
    date: "Mar 20, 2026 - Present",
    description: "Active upstream contribution to Kubespray for large-scale cluster deployments. Focusing on cgroup v2 migration pathways and automated bootstrap stability for production-ready bare-metal infrastructure.",
    skills: ["Go", "Kubernetes", "Ansible", "Terraform", "Cloud Infrastructure", "Systems Architecture"],
    githubUrl: "https://github.com/johnnietse/kubespray",
  },
  "ApplicaAI - AI-Powered Job Assistant": {
    title: "ApplicaAI - AI-Powered Job Assistant",
    date: "Aug 2025 - Jan 10, 2026",
    description: "Production-grade AI SaaS resume builder architecting a streaming chat system using Vercel AI SDK. Orchestrates 13 LLM models across 3 providers with Redis-backed leaky bucket rate limiting and Supabase PostgreSQL backend with JSONB storage.",
    skills: ["Next.js", "React", "Python", "Supabase", "Stripe", "Docker", "LangGraph", "Redis"],
    githubUrl: "https://github.com/johnnietse/AI-Powered_Professional_Job_Application_Assistant",
  },
  "High-Fidelity Engineering Portfolio (v2)": {
    title: "High-Fidelity Engineering Portfolio (v2)",
    date: "Mar 26, 2026 - Present",
    description: "The very site you are viewing. Developed with Next.js 16 and React 19, featuring an interactive 3D WebGL Command Center, custom HUD components, and real-time GitHub synchronization using the GraphQL API.",
    skills: ["Next.js 16", "React 19", "Three.js", "WebGL", "GraphQL API", "Framer Motion", "Tailwind CSS"],
    githubUrl: "https://github.com/johnnietse/personal-portfolio-website",
  },
  "Automated Stock Trading Agent (DQN)": {
    title: "Automated Stock Trading Agent (DQN)",
    date: "May 2025 - Present",
    description: "Intelligent stock trading agent leveraging Reinforcement Learning (DQN) and OpenAI Gym. Trained on historical data with technical indicators (EMA, MACD, RSI), featuring experience replay and epsilon-greedy exploration for optimal trading policies.",
    skills: ["Python", "Machine Learning", "Reinforcement Learning", "DQN", "OpenAI Gym", "Matplotlib"],
    githubUrl: "https://github.com/johnnietse/Deep-Q-Network-reinforcement-learning-stock-trading",
  },
  "PortraitArt Gallery": {
    title: "PortraitArt Gallery",
    date: "Jun 2025 - Mar 13, 2026",
    description: "Full-stack web application leveraging U\u00B2-Net architecture for salient object detection to transform images into high-quality artistic portraits. Features custom-built PyTorch inference pipeline and OpenCV morphological mask refinement for professional edge quality.",
    skills: ["Python", "PyTorch", "Flask", "React", "OpenCV", "Deep Learning", "U\u00B2-Net Architecture"],
    githubUrl: "https://github.com/johnnietse/Portrait_Gallery",
  },
  "Algorithmic Cryptocurrency Trading System (v2)": {
    title: "Algorithmic Cryptocurrency Trading System (v2)",
    date: "May 2025 - Jan 5, 2026",
    description: "Modular backtesting system for 28+ assets with a 5-stage pipeline. Engineered an API management layer with exponential backoff and calculated critical KPIs including Sharpe Ratio (2.69) and Maximum Drawdown across volatile markets.",
    skills: ["Python", "Pandas", "Scikit-Learn", "API Architecture", "Quantitative Analysis", "Risk Analytics", "Jupyter"],
    githubUrl: "https://github.com/johnnietse/cryptocurrency-trading-system-with-coingecko-api",
  },
  "RISC-V CPU Architecture": {
    title: "RISC-V CPU Architecture",
    date: "Sep 2024 - Feb 10, 2026",
    description: "32-bit single-cycle RISC-V processor architected in VHDL/Verilog for ELEC 374. Features a complete instruction set (R-type, I-type, S-type, B-type) with integrated ALUs, control units, and hazard detection logic.",
    skills: ["VHDL", "Verilog", "RISC-V", "CPU Design", "Digital Logic", "FPGA"],
    githubUrl: "https://github.com/johnnietse/RISC_V_CPU",
  },
  "L4 Autonomous Vehicle Object Detection": {
    title: "L4 Autonomous Vehicle Object Detection",
    date: "Aug 2025 - Mar 20, 2026",
    description: "Custom YOLOv8 training pipeline for the Queen's AutoDrive team. Orchestrated large-scale dataset labeling and model fine-tuning to achieve high-precision detection of urban driving obstacles (cones, pedestrians, signals).",
    skills: ["Python", "YOLOv8", "OpenCV", "Dataset Labeling", "TensorFlow", "AutoDrive"],
    githubUrl: "https://github.com/johnnietse/L4-autonomous-vehicle-object-detection-model-training",
  },
  "Flight Planning System": {
    title: "Flight Planning System",
    date: "Jan 2024 - Mar 25, 2026",
    description: "Robust Java-based flight trajectory planning system. Implemented Dijkstra's algorithm and graph-based data structures to calculate optimal paths with real-time constraint handling for multi-leg air travel.",
    skills: ["Java", "Data Structures", "Dijkstra's Algorithm", "Graph Theory", "Software Engineering"],
    githubUrl: "https://github.com/johnnietse/Flight_planning_system",
  },
  "PDF Chatbot (RAG System)": {
    title: "PDF Chatbot (RAG System)",
    date: "Mar 2025 - Feb 15, 2026",
    description: "Intelligent document assistant using LangChain and OpenAI's GPT-3.5-turbo. Employs PyPDFLoader for semantic chunking and ChromaDB for vector retrieval-augmented generation (RAG).",
    skills: ["Python", "Flask", "LangChain", "Docker", "RAG", "ChromaDB", "Vector Embeddings"],
    githubUrl: "https://github.com/johnnietse/pdf-chatbot",
  },
  "FYIC 2025 Conference Website": {
    title: "FYIC 2025 Conference Website",
    date: "Mar 2025 - Feb 18, 2026",
    description: "High-traffic server-side rendered application for 18+ universities. Automated image optimization using Sharp (95+ Lighthouse score) and orchestrated GitHub Actions for zero-downtime Vercel/Cloudflare deployments.",
    skills: ["Next.js 15", "TypeScript", "Tailwind CSS", "CI/CD", "Node.js", "WCAG 2.1 AA", "GitHub Actions"],
    githubUrl: "https://github.com/johnnietse/2025-fyic",
  },
  "Deel Legal Intelligence AI": {
    title: "Deel Legal Intelligence AI",
    date: "Feb 7, 2026",
    description: "Advanced RAG-based legal analysis engine designed for contract compliance and clause identification. Utilizes recursive character splitting and specialized vector index tuning for high-precision legal document retrieval.",
    skills: ["Python", "RAG", "LangChain", "OpenAI API", "Legal Tech", "Vector Databases"],
    githubUrl: "https://github.com/johnnietse/deel-legal-ai",
  },
  "Summer of Code Debian Technical Proposal": {
    title: "Summer of Code Debian Technical Proposal",
    date: "Mar 22, 2026",
    description: "Formal architectural proposal for the Debian Summer of Code 2026, focusing on infrastructure automation and package management optimization.",
    skills: ["HTML", "Technical Writing", "Debian Infrastructure", "Systems Research"],
    githubUrl: "https://github.com/johnnietse/Summer_of_code_proposal_Debian_2026",
  },
  "GitHub Analytics Command Center": {
    title: "GitHub Analytics Command Center",
    date: "Mar 27, 2026",
    description: "Internal data engine used to synchronize repository metadata, activity streams, and technical skill clusters for this portfolio portfolio. Powered by Python and GitHub REST/GraphQL APIs.",
    skills: ["Python", "GitHub API", "Data Analytics", "JSON Processing", "Automation"],
    githubUrl: "https://github.com/johnnietse/github-analytics",
  },
  "HPC Deep Learning": {
    title: "HPC Deep Learning",
    date: "Sep 2024 - Dec 20, 2025",
    description: "High-performance deep learning repository for ELEC 475. Implemented distributed training of CNNs on GPU clusters, focusing on batch-normalization optimization and memory-efficient compute.",
    skills: ["Python", "PyTorch", "HPC", "CUDA", "CNN Training", "Distributed Systems"],
    githubUrl: "https://github.com/johnnietse/ELEC-475",
  },
  "Virtual Try-On: Clothing AI": {
    title: "Virtual Try-On: Clothing AI",
    date: "Jun 2025 - Dec 15, 2025",
    description: "Perspective transformation-based clothing overlay utilizing cvzone's PoseModule and OpenCV warping functions. Implemented semi-transparent overlay blending and green screen removal for realistic media streaming.",
    skills: ["Python", "Flask", "OpenCV", "Computer Vision", "Pose Estimation", "Warping Functions"],
    githubUrl: "https://github.com/johnnietse/cloth-try-on",
  },
  "Local LLM PDF Chatbot": {
    title: "Local LLM PDF Chatbot",
    date: "Apr 2025 - Dec 5, 2025",
    description: "Privacy-centric RAG system using local LLMs (via Ollama/LlamaCpp). Integrates LangChain for document ingestion and ChromaDB as a local vector store, ensuring data never leaves the host machine.",
    skills: ["Python", "LangChain", "Ollama", "ChromaDB", "LlamaCpp", "Local AI"],
    githubUrl: "https://github.com/johnnietse/localLLM-pdf-chatbot",
  },
  "YOLO Dataset Visualizer": {
    title: "YOLO Dataset Visualizer",
    date: "Jun 2025 - Jul 11, 2025",
    description: "Web-based validation tool for YOLO object detection datasets. Accelerates ML pipelines by providing rapid batch visual verification of bounding boxes and class-label mappings with ZIP export capability.",
    skills: ["Python", "Flask", "OpenCV", "Tailwind CSS", "Machine Learning", "Dataset Validation"],
    githubUrl: "https://github.com/johnnietse/boundingBoxVisualizer",
  },
  "Software Specifications Suite": {
    title: "Software Specifications Suite",
    date: "Sep 2024 - Jun 28, 2025",
    description: "Comprehensive documentation and formal modeling of complex software systems. Developed UML diagrams, state machines, and functional requirements for scalable enterprise architectures.",
    skills: ["UML", "Software Engineering", "Functional Specs", "Documentation", "Agile"],
    githubUrl: "https://github.com/johnnietse/software-specifications",
  },
  "Conference DB Management": {
    title: "Conference DB Management",
    date: "Jan 2025 - Jun 28, 2025",
    description: "Full-scale SQL database for conference orchestration. Designed normalized schemas (3NF/BCNF) and implemented complex triggers/procedures for registration, scheduling, and attendance tracking.",
    skills: ["SQL", "Database Design", "PostgreSQL", "Stored Procedures", "Normalization", "PHP"],
    githubUrl: "https://github.com/johnnietse/conference-database-management-system",
  },
  "XML Annotation Processor": {
    title: "XML Annotation Processor",
    date: "May 2025 - Jun 28, 2025",
    description: "Python-based utility for mass processing of machine learning annotations. Automates the transformation of XML (Pascal VOC) to TXT (YOLO) formats with data augmentation and validation checks.",
    skills: ["Python", "XML Parsing", "Machine Learning Data", "Computer Vision", "Automation"],
    githubUrl: "https://github.com/johnnietse/XML-annotation-batch-processor",
  },
  "Classic Pacman Engine": {
    title: "Classic Pacman Engine",
    date: "Jan 2024 - Jun 28, 2025",
    description: "Classic arcade game recreation in Java/Python. Implemented A* pathfinding for ghost AI behavior and collision detection algorithms for real-time gameplay optimization.",
    skills: ["Java", "AI Pathfinding", "Game Engine", "A* Algorithm", "Collision Detection"],
    githubUrl: "https://github.com/johnnietse/pacman-game",
  },
  "Walk-Jump Motion Classifier": {
    title: "Walk-Jump Motion Classifier",
    date: "Jun 2, 2025",
    description: "Human activity recognition system using IMU sensor data. Trained a Random Forest classifier to distinguish between walking, jumping, and stationary states with high temporal precision.",
    skills: ["Python", "Machine Learning", "Scikit-Learn", "IMU Sensors", "Signal Processing"],
    githubUrl: "https://github.com/johnnietse/walk-jump-motion-classifier",
  },
  "GuessMaster Android Game": {
    title: "GuessMaster Android Game",
    date: "May 2024 - Jun 2025",
    description: "Interactive Android quiz application developed in Java. Features a modular activity-based architecture with dynamic ranking systems and persistent user score storage.",
    skills: ["Android", "Java", "Mobile UX", "SQLite", "Activity Lifecycle"],
    githubUrl: "https://github.com/johnnietse/guessmaster-android-game",
  },
  "Excel Data Modeling": {
    title: "Excel Data Modeling",
    date: "Jan 2025 - Mar 20, 2026",
    description: "Complex financial modeling and cell-lineage data analysis initially in Excel, now being integrated into lightweight C-based terminal spreadsheeting tools.",
    skills: ["C", "Excel", "Power Query", "Data Analysis", "Financial Modeling"],
    githubUrl: "https://github.com/johnnietse/fundamental-cell-excel-spreadsheet",
  },
  "CUDA GPU Programming": {
    title: "CUDA GPU Programming",
    date: "Oct 2024 - May 16, 2025",
    description: "High-performance parallel algorithms implemented in CUDA C++. Optimized matrix multiplications, stencils, and reductions to achieve significant speedups over CPU-based baselines.",
    skills: ["CUDA", "C++", "Parallel Computing", "GPU Optimization", "Memory Architecture"],
    githubUrl: "https://github.com/johnnietse/cuda-GPU-programming",
  },
  "Arduino Rock-Paper-Scissors": {
    title: "Arduino Rock-Paper-Scissors",
    date: "Nov 2023 - Oct 19, 2024",
    description: "Hand-gestured interactive game using infrared sensors and Arduino. Engineered real-time gesture matching and competitive scoring logic for a physical hardware interface.",
    skills: ["Arduino", "C++", "Sensors", "Physical Computing", "Embedded Systems"],
    githubUrl: "https://github.com/johnnietse/arduino-rock-paper-scissors-duel",
  },
  "EV Battery Enclosure": {
    title: "EV Battery Enclosure",
    date: "Jan 2023 - Oct 19, 2024",
    description: "Mechanical design and BMS for an EV conversion. Engineered a custom aluminum enclosure with integrated liquid cooling, reducing peak thermal spikes by 40%.",
    skills: ["SolidWorks", "Embedded Systems", "Thermal Management", "EV Engineering", "C++"],
    githubUrl: "https://github.com/johnnietse/electric-vehicle-automated-battery-enclosure",
  },
  "Smart Home Security Platform": {
    title: "Smart Home Security Platform",
    date: "Oct 19, 2024",
    description: "Arduino-based physical security platform integrating PIR and ultrasonic sensors for intrusion detection. Features custom state-machine logic for comprehensive monitoring.",
    skills: ["Arduino", "Sensors", "I2C/SPI", "Hardware Interfacing", "State Machines"],
    githubUrl: "https://github.com/johnnietse/smart-home-security-system",
  },
  "Arduino Robotic Assistive Arm": {
    title: "Arduino Robotic Assistive Arm",
    date: "Aug 2023 - Oct 18, 2024",
    description: "AI-driven robotic arm integration for accessibility. Developed a computer vision pipeline using OpenCV to coordinate a 6-DOF Kinova arm with a Clearpath Jackal UGV.",
    skills: ["Robotics", "OpenCV", "Embedded Systems", "Kinova API", "ROS2", "C++"],
    githubUrl: "https://github.com/johnnietse/arduino-robotic-assistive-arm",
  },
  "Desktop Lighting IoT Lamp": {
    title: "Desktop Lighting IoT Lamp",
    date: "Dec 2024 - Oct 18, 2024",
    description: "IoT-enabled smart lamp project. Features custom PCB design with PWM-based dimming control and remote activation via ESP32 integration.",
    skills: ["ESP32", "IoT", "PCB Design", "PWM Control", "WiFi Integration"],
    githubUrl: "https://github.com/johnnietse/desktop-lighting-lamp",
  },
  "SolidWorks Camera Design": {
    title: "SolidWorks Camera Design",
    date: "Jan 2025 - Oct 18, 2024",
    description: "Mechanical design and casing for a robust security camera system. Modeled in SolidWorks with considerations for IP67 weatherproofing.",
    skills: ["SolidWorks", "Industrial Design", "CAD", "Weatherproofing", "Thermal Analysis"],
    githubUrl: "https://github.com/johnnietse/solidworks-security-camera",
  },
  "TaskMaster Productivity Suite": {
    title: "TaskMaster Productivity Suite",
    date: "Apr 2025",
    description: "Full-featured task management app with complex database schemas and PostgreSQL triggers for automated profiling. Implemented row-level security (RLS) for data isolation.",
    skills: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "RLS"],
    githubUrl: "https://github.com/johnnietse/manage-mode-ui",
  },
  "Workout Streak Hub": {
    title: "Workout Streak Hub",
    date: "Apr 2025",
    description: "Personal fitness tracker developed with modern React patterns and Supabase authentication. Features daily workout logging, progress visualization, and CI/CD on Vercel.",
    skills: ["React", "Vite", "TypeScript", "Supabase", "Vercel", "Tailwind CSS"],
    githubUrl: "https://github.com/johnnietse/workout-streak-hub",
  },
  travelExpenseTracker: {
    title: "travelExpenseTracker",
    date: "Dec 2024 - Jun 22, 2025",
    description: "Android finance app with SQLite-backed authentication and real-time spending analytics using MPAndroidChart for competition teams.",
    skills: ["Kotlin", "Java", "Android Studio", "SQLite", "MPAndroidChart", "Mobile Dev"],
    githubUrl: "https://github.com/johnnietse/travelExpenseTracker",
  },
  "ChillnCharm Ecommerce Engine": {
    title: "ChillnCharm Ecommerce Engine",
    date: "May 2024 - Aug 2024",
    description: "Android e-commerce prototype built with MVVM and Clean Architecture. Integrates Retrofit and ROOM for localized SQLite caching.",
    skills: ["Android", "Kotlin", "MVVM", "Clean Architecture", "Retrofit", "ROOM Database"],
    githubUrl: "https://github.com/johnnietse/ChillnCharm",
  },
  "LinkedIn Connection Automator": {
    title: "LinkedIn Connection Automator",
    date: "Jun 3, 2025",
    description: "Python automation tool integrating Selenium and OpenCV template matching to identify UI states. Fault-tolerant workflow for educational technical demonstration.",
    skills: ["Python", "Selenium", "OpenCV", "Automation", "Computer Vision"],
    githubUrl: "https://github.com/johnnietse/linkedin-connection-automation-tool",
  },
  "ASL Hand Sign Detector": {
    title: "ASL Hand Sign Detector",
    date: "May 2025 - Jun 3, 2025",
    description: "Deep learning system for sign language recognition. Trained a custom CNN to classify ASL alphabets from live video feeds.",
    skills: ["Python", "TensorFlow", "Keras", "OpenCV", "Deep Learning"],
    githubUrl: "https://github.com/johnnietse/asl-hand-sign-detector",
  },
  "Enterprise Stock Dashboard": {
    title: "Enterprise Stock Dashboard",
    date: "May 2025",
    description: "Comprehensive financial analytics suite built with Power BI and Excel Power Query. Normalizes disparate market data into interactive visualizations.",
    skills: ["Power BI", "Excel Power Query", "Data Visualization", "Financial Modeling"],
    githubUrl: "https://github.com/johnnietse/stock-dashboard",
  },
  "Mobile Virtual Try-On (AR)": {
    title: "Mobile Virtual Try-On (AR)",
    date: "Jul 2025 - Dec 1, 2025",
    description: "Experimental mobile application utilizing augmented reality and Pose Estimation to simulate clothing trial for e-commerce platforms.",
    skills: ["Android", "OpenCV", "Pose Estimation", "AR", "Mobile Development", "Python"],
    githubUrl: "https://github.com/johnnietse/cloth-virtual-try-on",
  },
  "Algorithmic Crypto Trading (v1)": {
    title: "Algorithmic Crypto Trading (v1)",
    date: "Apr 2025 - Jul 11, 2025",
    description: "Initial prototype of a modular trading engine focusing on basic backtesting and historical data ingestion for limited assets.",
    skills: ["Python", "Pandas", "Quantitative Analysis", "Finance", "Jupyter"],
    githubUrl: "https://github.com/johnnietse/cryptocurrency-trading-system",
  },
  "Summer of Code Debian 2026": {
    title: "Summer of Code Debian 2026",
    date: "Mar 22, 2026",
    description: "Technical implementation research and proposal for automated package testing architectures within the Debian ecosystem.",
    skills: ["Technical Writing", "Linux Infrastructure", "Automation", "HTML"],
    githubUrl: "https://github.com/johnnietse/Summer_of_code_proposal_Debian_2026",
  },
  "Nios II Assembly Engineering": {
    title: "Nios II Assembly Engineering",
    date: "Jan 15, 2026",
    description: "Laboratory series focusing on Nios II Soft Processor architecture. Designed low-level interrupt handlers, memory-mapped I/O routines, and performance-tuned assembly algorithms.",
    skills: ["Assembly", "Nios II", "Embedded Systems", "Hardware Architecture"],
    githubUrl: "https://github.com/johnnietse/nios2-assembly-language-labs",
  },
  "Autonomous Mode CAN Bus DBC": {
    title: "Autonomous Mode CAN Bus DBC",
    date: "Jan 20, 2026",
    description: "DBC file architecture and message mapping for L4 autonomous vehicle mode switching via CAN bus. Defines critical safety messages and control unit arbitration logic.",
    skills: ["CAN Bus", "DBC", "Autonomous Driving", "Systems Engineering"],
    githubUrl: "https://github.com/johnnietse/LS-dbc-autonomous-mode",
  },
  "Contributor Playground": {
    title: "Contributor Playground",
    date: "Feb 18, 2026",
    description: "Sandboxed Docker environment for rapid testing of upstream Kubernetes patches and CI/CD workflow simulations.",
    skills: ["Docker", "Linux", "CI/CD", "Contributor Excellence"],
    githubUrl: "https://github.com/johnnietse/contributor-playground",
  },
  "Engineering Hub (Profile Data)": {
    title: "Engineering Hub (Profile Data)",
    date: "Jun 1, 2025",
    description: "Central configuration and meta-data engine for my GitHub profile, including automated status tracking and technical identity orchestration.",
    skills: ["Markdown", "Config Management", "GitHub Actions"],
    githubUrl: "https://github.com/johnnietse/johnnietse",
  },
  "Legacy Archive: First Repo": {
    title: "Legacy Archive: First Repo",
    date: "Aug 12, 2024",
    description: "My initial foray into open-source version control. Represents the foundational commit that started this engineering journey.",
    skills: ["Git", "Version Control", "Documentation"],
    githubUrl: "https://github.com/johnnietse/my-repo",
  },
  "Fyic 2025 Website (Prototype)": {
    title: "Fyic 2025 Website (Prototype)",
    date: "Dec 10, 2025",
    description: "Initial architectural prototype and skeleton for the FYIC 2025 conference platform.",
    skills: ["JavaScript", "HTML", "CSS", "Next.js Prototype"],
    githubUrl: "https://github.com/johnnietse/fyic-2025-website",
  },
  "GitHub Infrastructure Dashboard": {
    title: "GitHub Infrastructure Dashboard",
    date: "Mar 27, 2026",
    description: "Real-time analytics engine and dashboard interface for monitoring GitHub repository metrics and contribution velocity.",
    skills: ["Python", "API Orchestration", "Next.js", "Dashboard Engineering"],
    githubUrl: "https://github.com/johnnietse/github-stats",
  },
};

/** Flat array of all projects for iteration. */
export const PROJECT_LIST: Project[] = Object.values(PROJECTS);

/** First 4 projects with GitHub URLs — used as API fallback. */
export const FALLBACK_PROJECTS: Project[] = PROJECT_LIST.filter(p => p.githubUrl).slice(0, 4);
