import {
  Code, Terminal, Database, Cloud, Server, Shield, Cpu,
  Network, Globe, Settings, Layers, GitBranch, Package,
  Monitor, Smartphone, Brain, Eye, Search, Layout,
  FileText, Image, Video, Music, Map, Users, Zap,
  Activity, BookOpen, Award, Coffee, Rocket, Hash,
  Link, Workflow, Beaker, Clock, Calendar,
  Target, Folder, FolderOpen, CheckCircle, Star,
  Heart, Lightbulb, Palette, Edit3, Play, Pause,
  Wifi, Usb, Plug, Battery, Power, RefreshCw,
  Wind, Droplet, MapPin, Signal, Table, Box,
  Mail, Send, Inbox, Archive, ChevronDown,
  ChevronUp, Sparkles, Atom, Wrench, Hammer,
  Brush, Pen, Pencil, Eraser, Ruler, Scale,
  Gem, Diamond, Flame, Snowflake, Leaf,
  Mountain, Sun, Moon, Bolt,
  BarChart, Calculator, Gauge, Filter, List, Anchor, Radio,
  Building, FileCode, MessageSquare, Bot, CreditCard,
  Navigation,
} from 'lucide-react';

// Map skill names to Lucide icons - using only icons that exist in lucide-react
export const skillIconMap: Record<string, React.ReactNode> = {
  // Languages & Frameworks
  'HTML5': <Code size={16} />,
  'CSS': <Palette size={16} />,
  'JavaScript (JS)': <Zap size={16} />,
  'TypeScript 5.8': <Code size={16} />,
  'Tailwind CSS': <Wind size={16} />,
  'Bootstrap': <Box size={16} />,
  'Material Tailwind': <Palette size={16} />,
  'React.js & React Native': <Atom size={16} />,
  'Next.js': <Globe size={16} />,
  'Expo': <Rocket size={16} />,
  'Node.js': <Server size={16} />,
  'Express.js': <Link size={16} />,
  'Python': <Terminal size={16} />,
  'C': <Code size={16} />,
  'C++ & Embedded C++': <Cpu size={16} />,
  'Java': <Coffee size={16} />,
  'Kotlin': <Code size={16} />,
  'Go': <Send size={16} />,
  'Perl': <FileText size={16} />,
  'R': <BarChart size={16} />,
  'SQL': <Database size={16} />,
  'MongoDB': <Database size={16} />,
  'Mongoose': <Database size={16} />,
  'MySQL': <Database size={16} />,
  'PostgreSQL': <Database size={16} />,
  'Django': <Server size={16} />,
  'Flask': <Beaker size={16} />,
  'FastAPI': <Server size={16} />,
  'Spring Boot': <Coffee size={16} />,
  'Google Gemini': <Brain size={16} />,
  'LangChain': <Link size={16} />,
  'LangGraph': <GitBranch size={16} />,
  'Pinecone': <Database size={16} />,
  'ChromaDB': <Database size={16} />,
  'scikit-learn': <Brain size={16} />,
  'PyTorch': <Brain size={16} />,
  'TensorFlow & Lite': <Brain size={16} />,
  'Hugging Face': <MessageSquare size={16} />,
  'LLaMA & CTransformers': <Bot size={16} />,
  'pandas': <Table size={16} />,
  'NumPy': <Calculator size={16} />,
  'Matplotlib': <BarChart size={16} />,
  'Seaborn': <BarChart size={16} />,
  'OpenCV': <Eye size={16} />,
  'CVZone': <Eye size={16} />,
  'Assembly language': <Cpu size={16} />,
  'ROS2': <Bot size={16} />,
  'VHDL': <Cpu size={16} />,
  'SystemVerilog/Verilog': <Cpu size={16} />,
  'LaTeX': <FileText size={16} />,
  'Bash/Shell': <Terminal size={16} />,
  'Framer Motion': <Play size={16} />,
  'GSAP': <Zap size={16} />,
  'Three.js': <Box size={16} />,
  'Canvas Confetti': <Sparkles size={16} />,
  'Lucide & Heroicons': <Star size={16} />,
  'React Hook Form': <FileText size={16} />,
  'Vite': <Zap size={16} />,
  'GraphQL': <GitBranch size={16} />,
  'Webhooks': <Link size={16} />,
  'Context API': <Layers size={16} />,
  'Redux': <Package size={16} />,
  'Selenium': <CheckCircle size={16} />,
  'BeautifulSoup': <Beaker size={16} />,
  'Jest': <CheckCircle size={16} />,
  'Supertest': <CheckCircle size={16} />,
  'OpenMPI': <Network size={16} />,
  'OpenMP': <Network size={16} />,
  'Room Database': <Database size={16} />,
  'Retrofit': <Link size={16} />,
  'Android Jetpack Compose': <Smartphone size={16} />,
  'Next.js API Routes': <Server size={16} />,
  'Nodemailer (SMTP)': <Mail size={16} />,
  'Sharp': <Edit3 size={16} />,
  'PostCSS': <Palette size={16} />,
  'Autoprefixer': <RefreshCw size={16} />,
  'ESLint': <CheckCircle size={16} />,

  // Developer Tools
  'Kubernetes (SIG-Apps)': <Server size={16} />,
  'LeaderWorkerSet (LWS)': <Server size={16} />,
  'Kubespray & SIG Cluster Lifecycle': <Server size={16} />,
  'Docker': <Box size={16} />,
  'Helm': <Anchor size={16} />,
  'OpenShift Kubernetes': <Server size={16} />,
  'GitHub Actions CI/CD': <Workflow size={16} />,
  'GitLab CI': <GitBranch size={16} />,
  'Bitbucket': <GitBranch size={16} />,
  'Jira (Scrum)': <List size={16} />,
  'Confluence': <FileText size={16} />,
  'Jenkins': <Settings size={16} />,
  'Ansible': <Settings size={16} />,
  'Terraform': <Layers size={16} />,
  'AWS (EC2, S3, Lambda, SQS, SNS)': <Cloud size={16} />,
  'AWS CloudWatch & Step Function': <Cloud size={16} />,
  'Azure & Azure Kubernetes Service (AKS)': <Cloud size={16} />,
  'Google Cloud Platform (GCP)': <Cloud size={16} />,
  'Vercel': <Rocket size={16} />,
  'Cloudflare': <Shield size={16} />,
  'Supabase (PostgreSQL with RLS)': <Database size={16} />,
  'Firebase': <Database size={16} />,
  'Render': <Play size={16} />,
  'MySQL Database': <Database size={16} />,
  'PostgreSQL / SQLite': <Database size={16} />,
  'Redis': <Database size={16} />,
  'Prisma': <Database size={16} />,
  'Stripe': <CreditCard size={16} />,
  'Excel (Dynamic Arrays & Stock Data)': <Table size={16} />,
  'SharePoint': <Folder size={16} />,
  'Dataverse': <Database size={16} />,
  'Power Automate': <Workflow size={16} />,
  'SAP S/4HANA Cloud': <Building size={16} />,
  'ORACLE Database': <Database size={16} />,
  'Microsoft Power BI': <BarChart size={16} />,
  'Raspberry Pi 5': <Cpu size={16} />,
  'PREEMPT_RT Linux': <Terminal size={16} />,
  'ValueCAN 4 & DBC Parsing': <Network size={16} />,
  'XML-driven config': <FileCode size={16} />,
  'MPMC zero-copy ROS–CAN transfer': <Network size={16} />,
  'CAN bus': <Network size={16} />,
  'SPI / I2C / UART': <Usb size={16} />,
  'nRF52840 / ESP32 / Arduino / RF': <Radio size={16} />,
  'Cyclone V FPGA': <Cpu size={16} />,
  'RISC-V ISA': <Cpu size={16} />,
  'Thread mesh networking': <Wifi size={16} />,
  'Coral TPU & EfficientDet': <Cpu size={16} />,
  'CUDA & MPI': <Cpu size={16} />,
  'DVFS & RAPL': <Gauge size={16} />,
  'OpenConfig': <Settings size={16} />,
  'etcd & CoreDNS': <Database size={16} />,
  'Linux cgroup v1 deprecation': <Settings size={16} />,
  'pod DNS & DPANIC crashes': <Settings size={16} />,
  'structure-aware semantic chunking': <Brain size={16} />,
  'Random Forest & GridSearchCV': <Brain size={16} />,
  'Gini feature importance': <BarChart size={16} />,
  'legal interpretability & LLM hallucinations': <Brain size={16} />,
  'LLM-powered resume automation SaaS': <Bot size={16} />,
  'memory-efficient RAG chatbot': <Database size={16} />,
  'quantized LLaMA models (.gguf)': <Brain size={16} />,
  'context windows & token limits': <FileText size={16} />,
  'salient object segmentation (U²-Net)': <Eye size={16} />,
  'two-level nested U²-Net architecture': <Layers size={16} />,
  'OpenCV morphological mask refinement': <Edit3 size={16} />,
  'low-power autonomous object detection': <Eye size={16} />,
  'MVVM Clean Architecture & Repository pattern': <Layers size={16} />,
  'RESTful APIs & FAKE STORE REST API': <Server size={16} />,
  'API uptime & rate limiting': <Shield size={16} />,
  'CI/CD & modular codebase': <Workflow size={16} />,
  'Redis rate limiting & caching layer': <Database size={16} />,
  'Caffeine & resilience4j': <Coffee size={16} />,
  'multi-stage Docker builds & containerizing': <Box size={16} />,
  'data preprocessing': <Filter size={16} />,
  'offline functionality': <Wifi size={16} />,
  'CanLII (Legal Data Retrieval)': <FileText size={16} />,
  'pdfplumber': <FileText size={16} />,

  // Open Source
  'vLLM (llm-d ecosystem)': <Rocket size={16} />,
  'Energy-Aware Endpoint Picker Plugin (EPP)': <Zap size={16} />,
  'Multi-Objective Routing Engine': <Navigation size={16} />,
  'eBPF Telemetry & DCGM / RAPL metrics': <Gauge size={16} />,
  'Kubernetes 1.35 cgroup v1 deprecation': <Settings size={16} />,
  'SIG Apps upstream maintainers': <Users size={16} />,
  'SIG Cluster Lifecycle (kubespray)': <Server size={16} />,
  'LeaderWorkerSet (LWS) controller fixes': <Server size={16} />,
  'Go controller-runtime patches': <Code size={16} />,
  'CNCF Open Source Workflow': <Workflow size={16} />,
  'Kubernetes Enhancement Proposals (KEPs)': <FileText size={16} />,
  'Unit / Integration / E2E Testing': <CheckCircle size={16} />,
  'Ginkgo & Gomega test frameworks': <Beaker size={16} />,
  'Code Review & PR collaboration': <GitBranch size={16} />,
};

// Fallback icon for skills not in the map
export const fallbackSkillIcon = <Code size={16} />;

// Helper function to get icon for a skill
export function getSkillIcon(skillName: string): React.ReactNode {
  return skillIconMap[skillName] || fallbackSkillIcon;
}

// Skill categories for collapsible sections
export const skillCategories = [
  {
    id: 'languages',
    label: 'Languages & Frameworks',
    icon: <Code size={14} />,
    skills: [
      'HTML5', 'CSS', 'JavaScript (JS)', 'TypeScript 5.8', 'Tailwind CSS',
      'Bootstrap', 'Material Tailwind', 'React.js & React Native', 'Next.js',
      'Expo', 'Node.js', 'Express.js', 'Python', 'C', 'C++ & Embedded C++',
      'Java', 'Kotlin', 'Go', 'Perl', 'R', 'SQL', 'MongoDB', 'Mongoose',
      'MySQL', 'PostgreSQL', 'Django', 'Flask', 'FastAPI', 'Spring Boot',
      'Google Gemini', 'LangChain', 'LangGraph', 'Pinecone', 'ChromaDB',
      'scikit-learn', 'PyTorch', 'TensorFlow & Lite', 'Hugging Face',
      'LLaMA & CTransformers', 'pandas', 'NumPy', 'Matplotlib', 'Seaborn',
      'OpenCV', 'CVZone', 'Assembly language', 'ROS2', 'VHDL',
      'SystemVerilog/Verilog', 'LaTeX', 'Bash/Shell', 'Framer Motion',
      'GSAP', 'Three.js', 'Canvas Confetti', 'Lucide & Heroicons',
      'React Hook Form', 'Vite', 'GraphQL', 'Webhooks', 'Context API',
      'Redux', 'Selenium', 'BeautifulSoup', 'Jest', 'Supertest',
      'OpenMPI', 'OpenMP', 'Room Database', 'Retrofit',
      'Android Jetpack Compose', 'Next.js API Routes', 'Nodemailer (SMTP)',
      'Sharp', 'PostCSS', 'Autoprefixer', 'ESLint',
    ],
  },
  {
    id: 'tools',
    label: 'Developer Tools & Workflows',
    icon: <Wrench size={14} />,
    skills: [
      'Kubernetes (SIG-Apps)', 'LeaderWorkerSet (LWS)', 'Kubespray & SIG Cluster Lifecycle',
      'Docker', 'Helm', 'OpenShift Kubernetes', 'GitHub Actions CI/CD',
      'GitLab CI', 'Bitbucket', 'Jira (Scrum)', 'Confluence', 'Jenkins',
      'Ansible', 'Terraform', 'AWS (EC2, S3, Lambda, SQS, SNS)',
      'AWS CloudWatch & Step Function', 'Azure & Azure Kubernetes Service (AKS)',
      'Google Cloud Platform (GCP)', 'Vercel', 'Cloudflare',
      'Supabase (PostgreSQL with RLS)', 'Firebase', 'Render',
      'MySQL Database', 'PostgreSQL / SQLite', 'Redis', 'Prisma', 'Stripe',
      'Excel (Dynamic Arrays & Stock Data)', 'SharePoint', 'Dataverse',
      'Power Automate', 'SAP S/4HANA Cloud', 'ORACLE Database',
      'Microsoft Power BI', 'Raspberry Pi 5', 'PREEMPT_RT Linux',
      'ValueCAN 4 & DBC Parsing', 'XML-driven config',
      'MPMC zero-copy ROS–CAN transfer', 'CAN bus', 'SPI / I2C / UART',
      'nRF52840 / ESP32 / Arduino / RF', 'Cyclone V FPGA', 'RISC-V ISA',
      'Thread mesh networking', 'Coral TPU & EfficientDet', 'CUDA & MPI',
      'DVFS & RAPL', 'OpenConfig', 'etcd & CoreDNS',
      'Linux cgroup v1 deprecation', 'pod DNS & DPANIC crashes',
    ],
  },
  {
    id: 'concepts',
    label: 'Data, ML & Engineering Concepts',
    icon: <Brain size={14} />,
    skills: [
      'structure-aware semantic chunking', 'Random Forest & GridSearchCV',
      'Gini feature importance', 'legal interpretability & LLM hallucinations',
      'LLM-powered resume automation SaaS', 'memory-efficient RAG chatbot',
      'quantized LLaMA models (.gguf)', 'context windows & token limits',
      'salient object segmentation (U²-Net)', 'two-level nested U²-Net architecture',
      'OpenCV morphological mask refinement', 'low-power autonomous object detection',
      'MVVM Clean Architecture & Repository pattern', 'RESTful APIs & FAKE STORE REST API',
      'API uptime & rate limiting', 'CI/CD & modular codebase',
      'Redis rate limiting & caching layer', 'Caffeine & resilience4j',
      'multi-stage Docker builds & containerizing', 'data preprocessing',
      'offline functionality', 'CanLII (Legal Data Retrieval)', 'pdfplumber',
    ],
  },
  {
    id: 'opensource',
    label: 'Open-Source Contributions',
    icon: <GitBranch size={14} />,
    skills: [
      'vLLM (llm-d ecosystem)', 'Energy-Aware Endpoint Picker Plugin (EPP)',
      'Multi-Objective Routing Engine', 'eBPF Telemetry & DCGM / RAPL metrics',
      'Kubernetes 1.35 cgroup v1 deprecation', 'SIG Apps upstream maintainers',
      'SIG Cluster Lifecycle (kubespray)', 'LeaderWorkerSet (LWS) controller fixes',
      'Go controller-runtime patches', 'CNCF Open Source Workflow',
      'Kubernetes Enhancement Proposals (KEPs)', 'Unit / Integration / E2E Testing',
      'Ginkgo & Gomega test frameworks', 'Code Review & PR collaboration',
    ],
  },
];
